name: Update README (daily)

on:
  schedule:
    - cron: "0 */12 * * *"   # a cada 12h
  workflow_dispatch:         # permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm i node-fetch@3

      - name: Generate dynamic section
        run: node .github/scripts/update-readme.js
        env:
          GITHUB_USER: "Deyyymore"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add README.md
            git commit -m "chore(readme): auto-update"
            git push
          fi
